[build-system]
requires = ["setuptools>=45", "wheel", "pip>=21.0"]
build-backend = "setuptools.build_meta"

[project]
name = "enterprise-rag"
version = "1.0.0"
description = "Enterprise-grade RAG System"
requires-python = ">=3.9"

[tool.setuptools]
package-dir = {"" = "src"}
